using BurmesePoker.Domain.Abstractions;

namespace BurmesePoker.Domain.Agents;

/// <summary>
/// One rung of the ladder, as something a person could be offered as an opponent: what it is
/// called, what it plays like in a sentence, how strong it is known to be, and how to seat a
/// fresh one.
/// </summary>
/// <remarks>
/// <para>
/// <b>The name is the join key</b> (BUILD-PLAN §3.8 item 4). It is what a CSV row, a journal
/// header and a command line all attribute a result to, so <b>a name never changes</b>: rename
/// a rung and yesterday's numbers stop being comparable.
/// </para>
/// <para>
/// ⚠️ <b>A name may not contain <c>#</c>, and that is a rule rather than a tidiness.</b> The
/// tournament's null cell seats one strategy twice under <c>"{name}#mirror"</c>
/// (<c>Tournament.MirrorSuffix</c>) — a <em>label</em> put on a copy so the harness can measure
/// its own bias, and not a way of playing. A front end offering <c>greedy#mirror</c> as an
/// opponent would be absurd, so the suffix was chosen to be unusable here and this constructor
/// is where that is enforced.
/// </para>
/// </remarks>
/// <param name="Name">What results are attributed to. Stable for ever; see above.</param>
/// <param name="Description">
/// One line, <b>written for somebody choosing an opponent</b> rather than for a reader of the
/// build plan. It says what the player is like, not which decision was added to make it.
/// </param>
/// <param name="Strength">
/// How strong this rung is <em>known</em> to be, as a level rather than as a score: higher is
/// stronger, and <b>rungs that measurement cannot separate share a number</b>.
/// <para>
/// ⚠️ <b>It is an ordinal, and it is not a measurement.</b> The measurements live in
/// <c>docs/strategy/measurements.csv</c> and are regenerated by <c>sim suite</c>; this is the
/// reading of them that a menu needs, so that a list of opponents can be shown strongest
/// first. As of P17: <c>greedy</c> and <c>cautious</c> come back at +20.30 and +20.28 mean
/// margin with the head-to-head between them <c>−0.2 ± 1.0</c>, verdict <em>inside the
/// interval</em> — so they are one level, and pretending otherwise would put a difference in
/// front of a person that nobody can feel because it is not there (§3.12 item 2).
/// </para>
/// </param>
/// <param name="Create">
/// Makes a new agent for one seat of one game, from that seat's seed. <b>Called per seat, never
/// shared</b> — an agent that remembered anything across games would make a run depend on the
/// order its games happened to be scheduled in, which is the determinism P12 stands on.
/// <para>
/// ⚠️ <b>The seed is the argument because a strategy may not reach for
/// <see cref="Random.Shared"/></b> (BUILD-PLAN §3.7 item 1, P15). Rungs that decide nothing at
/// random ignore it; <see cref="RandomBotAgent"/> is why it is here at all.
/// </para>
/// </param>
public sealed record BotRung(string Name, string Description, int Strength, Func<int, IPlayerAgent> Create)
{
    /// <summary>What a name may not contain, and why is in the remarks above.</summary>
    public const char Reserved = '#';

    private readonly string _name = Checked(Name);

    /// <inheritdoc cref="BotRung" />
    /// <remarks>
    /// ⚠️ <b>Checked in the accessor and not in an initialiser</b>, which is the difference
    /// between a rule and a suggestion: a record's <c>with</c> expression copies the backing
    /// fields and then sets what changed, so a property initialiser runs on construction only.
    /// <c>rung with { Name = "greedy#mirror" }</c> is precisely how the harness makes its copy,
    /// and precisely what this has to refuse. <b>Found by writing the test that says so.</b>
    /// </remarks>
    public string Name
    {
        get => _name;
        init => _name = Checked(value);
    }

    private static string Checked(string name)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);

        return name.Contains(Reserved, StringComparison.Ordinal)
            ? throw new ArgumentException(
                $"'{name}' is not a name a rung may have: '{Reserved}' is reserved for the labels the "
                + "harness puts on a copy of a rung (Tournament.MirrorSuffix), which are not ways of playing.",
                nameof(name))
            : name;
    }
}

/// <summary>
/// Every way the computer knows how to play, named once for the whole solution.
/// </summary>
/// <remarks>
/// <para>
/// <b>The one list</b> (BUILD-PLAN P18). Until this packet there were four independent notions
/// of <em>which bot</em> — the harness's catalog, a private two-value enum in the console, two
/// hard-coded <c>new</c>s in the browser client and a default factory on the server's options —
/// so a fifth rung meant editing four places and the browser would still not have offered it.
/// It is here rather than in a front end because the agents are here, and it is only a name and
/// a factory, so it does no I/O and breaks no layering rule (§2).
/// </para>
/// <para>
/// ⚠️ <b>Two orders, and they answer different questions.</b> <see cref="All"/> is <b>ladder
/// order</b> — each rung differs from the one above it in exactly one decision (P15) — which is
/// what a research instrument wants and what the harness's reports are ordered by.
/// <see cref="ByStrength"/> is <b>strongest first</b>, which is what a person choosing an
/// opponent wants. Neither is derivable from the other: the ladder is ordered by what was added
/// and the menu by what was measured.
/// </para>
/// <para>
/// ⚠️ <b>This is not the difficulty dial</b> (§3.12). A ladder is a research instrument whose
/// rungs need not be evenly spaced, need not be complete, and — <c>simple</c> being the example
/// — play a <em>different and worse idea</em> rather than the right idea badly. P19 builds the
/// dial on top of this; P18 only stops there being four lists.
/// </para>
/// </remarks>
public static class BotCatalog
{
    /// <summary>
    /// Everything nameable, <b>in ladder order</b>: each rung differs from the one above it in
    /// exactly one decision (BUILD-PLAN P15).
    /// </summary>
    public static IReadOnlyList<BotRung> All { get; } =
    [
        new(
            "random",
            "Knows the rules and nothing else — takes whatever is in front of it and throws away whatever it happens to touch.",
            Strength: 0,
            seed => new RandomBotAgent(new Random(seed))),
        new(
            "simple",
            "Holds on to whatever already melds, and throws the first card it can spare.",
            Strength: 1,
            _ => new SimpleBotAgent()),
        new(
            "greedy",
            "Keeps the cards with partners as well as the melds, so its hand builds towards something.",
            Strength: 2,
            _ => new GreedyBotAgent()),
        new(
            "cautious",
            "Plays like the last one, and thinks about what the card it is throwing is worth to whoever picks it up.",
            Strength: 2,
            _ => new CautiousBotAgent()),
        new(
            "counting",
            "Plays like the last one, and remembers the cards it has watched go by.",
            Strength: 2,
            _ => new CountingBotAgent())
    ];

    /// <summary>
    /// The same rungs, <b>strongest first</b> — what a menu of opponents is ordered by.
    /// </summary>
    /// <remarks>
    /// Ties keep ladder order, so a level that measurement cannot split is shown in the order
    /// it was built. <b>A permutation of <see cref="All"/> and never a subset</b>, which is a
    /// test.
    /// </remarks>
    public static IReadOnlyList<BotRung> ByStrength { get; } =
        [.. All.OrderByDescending(rung => rung.Strength)];

    /// <summary>
    /// The strongest rung there is.
    /// </summary>
    /// <remarks>
    /// ⚠️ <b>What stands in for a seat nobody is answering, and what a hint is asked of</b> —
    /// neither of which is the table's difficulty setting. A stand-in that played worse than the
    /// table does would be worth less than no stand-in (P13.1), and a hint that got worse as you
    /// lowered the difficulty would be absurd. Both are said again where they are used, because
    /// both look like oversights to somebody tidying up.
    /// </remarks>
    public static BotRung Hardest => ByStrength[0];

    /// <summary>Looks a rung up by name, case-insensitively.</summary>
    /// <exception cref="ArgumentException">No rung is called that.</exception>
    public static BotRung Resolve(string name) =>
        Find(name)
        ?? throw new ArgumentException(
            $"No bot called '{name}'. Known: {string.Join(", ", All.Select(rung => rung.Name))}.", nameof(name));

    /// <summary>Looks a rung up by name, or null if there is none.</summary>
    /// <remarks>
    /// For a front end taking a name off a command line or a form, where an unknown one is
    /// something to fall back from rather than to throw over.
    /// </remarks>
    public static BotRung? Find(string? name) =>
        All.FirstOrDefault(rung => string.Equals(rung.Name, name, StringComparison.OrdinalIgnoreCase));
}
