using BurmesePoker.Domain.Abstractions;

namespace BurmesePoker.Domain.Agents;

/// <summary>
/// What settles how good a rung is — which of the programme's instruments has the answer.
/// </summary>
/// <remarks>
/// <para>
/// 🔥 <b>Until P22 every rung answered one question and the question was <em>which way of
/// playing wins more rounds</em>.</b> A rung whose decision reads the <b>stakes</b> does not:
/// the stakes are fixed at the start of a game and are not a rule (RULES.md §4.3), so
/// <c>prospector</c> is literally <c>outs</c> at $5/$1 and a different player at $5/$40, and
/// <em>"how good is it"</em> has no answer until somebody says what the table is played for.
/// </para>
/// <para>
/// ⚠️ <b>So it is measured somewhere else, and that is a statement about the instrument rather
/// than about the rung.</b> The ladder tournament ranks a field that all play one stakes; a
/// rung ranked on <see cref="Money"/> is measured by the money sweep instead, over four ratios,
/// against the top of the ladder. <b>Every rung is measured by exactly one of the two</b>, and
/// <c>StandingAnswerTests</c> is what says so — which is the same guarantee P18 and P20 built
/// one layer at a time, now made total.
/// </para>
/// <para>
/// ⚠️ <b>P44 added a second reason to be money-ranked, and it is not stakes-sensitivity.</b>
/// <c>purist</c> reads no stakes at all — it is the same player at every ratio — but its whole
/// idea is trading rounds for a multiplied prize (RULES.md §7.3), so win rate would misjudge it
/// <em>by construction</em> rather than by noise. What <see cref="Money"/> actually declares is
/// <em>which currency settles this rung</em>; whether the rung varies with the stakes is a fact
/// the sweep discovers, not one the enum encodes.
/// </para>
/// <para>
/// 🔥 <b>And it is not only a saving of wall clock.</b> Putting <c>prospector</c> in the ladder
/// field costs six head-to-head cells that reproduce a fact a unit test already asserts
/// (<c>MoneySweepTests.AtTheStandardStakesTheTwoRungsPlayOneGameUnderTwoNames</c>) — but it also
/// grows the Holm family those six cells are corrected in, and <b>a null cell added to a family
/// makes every real verdict in it harder to reach.</b> A duplicate is not a free row.
/// </para>
/// </remarks>
public enum RankedOn
{
    /// <summary>Win rate, in a field that all play one stakes — the ladder tournament.</summary>
    WinRate,

    /// <summary>Money a round, swept across stakes ratios — the money sweep (BUILD-PLAN P22).</summary>
    Money
}

/// <summary>
/// One rung of the ladder, as something a person could be offered as an opponent: what it is
/// called, what it plays like in a sentence, how strong it is known to be, and how to seat a
/// fresh one.
/// </summary>
/// <remarks>
/// <para>
/// <b>The name is the join key</b> (BUILD-PLAN §3.8 item 4). It is what a CSV row, a journal
/// header and a command line all attribute a result to, so <b>a name never changes</b>: rename
/// a rung and yesterday's numbers stop being comparable.
/// </para>
/// <para>
/// ⚠️ <b>A name may not contain <c>#</c>, and that is a rule rather than a tidiness.</b> The
/// tournament's null cell seats one strategy twice under <c>"{name}#mirror"</c>
/// (<c>Tournament.MirrorSuffix</c>) — a <em>label</em> put on a copy so the harness can measure
/// its own bias, and not a way of playing. A front end offering <c>greedy#mirror</c> as an
/// opponent would be absurd, so the suffix was chosen to be unusable here and this constructor
/// is where that is enforced.
/// </para>
/// </remarks>
/// <param name="Name">What results are attributed to. Stable for ever; see above.</param>
/// <param name="Description">
/// One line, <b>written for somebody choosing an opponent</b> rather than for a reader of the
/// build plan. It says what the player is like, not which decision was added to make it.
/// </param>
/// <param name="Strength">
/// How strong this rung is <em>known</em> to be, as a level rather than as a score: higher is
/// stronger, and <b>rungs that measurement cannot separate share a number</b>.
/// <para>
/// ⚠️ <b>It is an ordinal, and it is not a measurement.</b> The measurements live in
/// <c>docs/strategy/measurements.csv</c> and are regenerated by <c>sim suite</c>; this is the
/// reading of them that a menu needs, so that a list of opponents can be shown strongest
/// first. As of P17: <c>greedy</c> and <c>cautious</c> come back at +20.30 and +20.28 mean
/// margin with the head-to-head between them <c>−0.2 ± 1.0</c>, verdict <em>inside the
/// interval</em> — so they are one level, and pretending otherwise would put a difference in
/// front of a person that nobody can feel because it is not there (§3.12 item 2).
/// </para>
/// </param>
/// <param name="Create">
/// Makes a new agent for one seat of one game, from that seat's seed. <b>Called per seat, never
/// shared</b> — an agent that remembered anything across games would make a run depend on the
/// order its games happened to be scheduled in, which is the determinism P12 stands on.
/// <para>
/// ⚠️ <b>The seed is the argument because a strategy may not reach for
/// <see cref="Random.Shared"/></b> (BUILD-PLAN §3.7 item 1, P15). Rungs that decide nothing at
/// random ignore it; <see cref="RandomBotAgent"/> is why it is here at all.
/// </para>
/// </param>
public sealed record BotRung(string Name, string Description, int Strength, Func<int, IPlayerAgent> Create)
{
    /// <summary>
    /// Which instrument settles how good this rung is (BUILD-PLAN P22, P23).
    /// </summary>
    /// <remarks>
    /// ⚠️ <b>Not a second strength and not a flag on the agent.</b> It says where the number
    /// lives, so that <c>sim suite</c> can measure every rung there is without measuring any
    /// rung twice — see <see cref="RankedOn"/> for why a stakes-reading rung cannot be ranked
    /// in a field played at one stakes.
    /// </remarks>
    public RankedOn Ranked { get; init; } = RankedOn.WinRate;

    /// <summary>What a name may not contain, and why is in the remarks above.</summary>
    public const char Reserved = '#';

    private readonly string _name = Checked(Name);

    /// <inheritdoc cref="BotRung" />
    /// <remarks>
    /// ⚠️ <b>Checked in the accessor and not in an initialiser</b>, which is the difference
    /// between a rule and a suggestion: a record's <c>with</c> expression copies the backing
    /// fields and then sets what changed, so a property initialiser runs on construction only.
    /// <c>rung with { Name = "greedy#mirror" }</c> is precisely how the harness makes its copy,
    /// and precisely what this has to refuse. <b>Found by writing the test that says so.</b>
    /// </remarks>
    public string Name
    {
        get => _name;
        init => _name = Checked(value);
    }

    private static string Checked(string name)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);

        return name.Contains(Reserved, StringComparison.Ordinal)
            ? throw new ArgumentException(
                $"'{name}' is not a name a rung may have: '{Reserved}' is reserved for the labels the "
                + "harness puts on a copy of a rung (Tournament.MirrorSuffix), which are not ways of playing.",
                nameof(name))
            : name;
    }
}

/// <summary>
/// Every way the computer knows how to play, named once for the whole solution.
/// </summary>
/// <remarks>
/// <para>
/// <b>The one list</b> (BUILD-PLAN P18). Until this packet there were four independent notions
/// of <em>which bot</em> — the harness's catalog, a private two-value enum in the console, two
/// hard-coded <c>new</c>s in the browser client and a default factory on the server's options —
/// so a fifth rung meant editing four places and the browser would still not have offered it.
/// It is here rather than in a front end because the agents are here, and it is only a name and
/// a factory, so it does no I/O and breaks no layering rule (§2).
/// </para>
/// <para>
/// ⚠️ <b>Two orders, and they answer different questions.</b> <see cref="All"/> is <b>ladder
/// order</b> — each rung differs from the one above it in exactly one decision (P15) — which is
/// what a research instrument wants and what the harness's reports are ordered by.
/// <see cref="ByStrength"/> is <b>strongest first</b>, which is what a person choosing an
/// opponent wants. Neither is derivable from the other: the ladder is ordered by what was added
/// and the menu by what was measured.
/// </para>
/// <para>
/// ⚠️ <b>This is not the difficulty dial</b> (§3.12). A ladder is a research instrument whose
/// rungs need not be evenly spaced, need not be complete, and — <c>simple</c> being the example
/// — play a <em>different and worse idea</em> rather than the right idea badly. P19 builds the
/// dial on top of this; P18 only stops there being four lists.
/// </para>
/// </remarks>
public static class BotCatalog
{
    /// <summary>
    /// Everything nameable, <b>in ladder order</b>: each rung differs from the one above it in
    /// exactly one decision (BUILD-PLAN P15).
    /// </summary>
    public static IReadOnlyList<BotRung> All { get; } =
    [
        new(
            "random",
            "Knows the rules and nothing else — takes whatever is in front of it and throws away whatever it happens to touch.",
            Strength: 0,
            seed => new RandomBotAgent(new Random(seed))),
        new(
            "simple",
            "Holds on to whatever already melds, and throws the first card it can spare.",
            Strength: 1,
            _ => new SimpleBotAgent()),
        new(
            "greedy",
            "Keeps the cards with partners as well as the melds, so its hand builds towards something.",
            Strength: 2,
            _ => new GreedyBotAgent()),
        new(
            "cautious",
            "Plays like the last one, and thinks about what the card it is throwing is worth to whoever picks it up.",
            Strength: 2,
            _ => new CautiousBotAgent()),
        new(
            "counting",
            "Plays like the last one, and remembers the cards it has watched go by.",
            Strength: 2,
            _ => new CountingBotAgent()),
        new(
            "outs",
            "Thinks about what it is still waiting for, and keeps the hand that more of the pack would help.",
            Strength: 3,
            _ => new OutsBotAgent()),
        new(
            "warden",
            "Plays like the last one, and will take a card it does not want to stop the player before it throwing another like it.",
            Strength: 3,
            _ => new WardenBotAgent()),
        new(
            "opportunist",
            "Never takes a card just to block you — but once a take has closed a rank against the player before it, it will not give that rank back.",
            Strength: 3,
            _ => new OpportunistBotAgent()),
        new(
            "prospector",
            "Plays like the last one, and would sooner dig in the deck than take what you threw — the deck's cards pay it and yours never will.",
            Strength: 3,
            _ => new ProspectorBotAgent())
        {
            // 🔥 The only rung whose decision reads the stakes, so the only one a field played
            // at one stakes cannot rank (BUILD-PLAN P22, and see RankedOn). It is measured, and
            // it is measured by the money sweep — docs/STRATEGY.md §10.
            Ranked = RankedOn.Money
        },
        new(
            "purist",
            "Never gives up a meld for it, but works its jokers out of its hand whenever that is free — a win without them is paid extra, and it plays for the extra.",
            Strength: 3,
            _ => new PuristBotAgent())
        {
            // 🔥 Money-ranked for the *other* reason a rung can be (see RankedOn): its decision
            // never reads the stakes, but its whole idea is trading win probability for a
            // multiplied prize (RULES.md §7.3), so a field ranked on declarations would misjudge
            // it by construction. Measured by the money sweep — docs/STRATEGY.md §14.
            Ranked = RankedOn.Money
        },
        new(
            "angler",
            "Weighs what you threw against the luck of the deck — and will pick up a card it cannot use yet, when it opens more doors than a blind draw would.",
            Strength: 3,
            _ => new AnglerBotAgent()),
        new(
            "sprinter",
            "Plays for the best hand until the end is in sight, then plays for the fastest one — near the line it keeps whatever is likeliest to win outright, not whatever is likeliest to improve.",
            Strength: 3,
            _ => new SprinterBotAgent())
    ];

    /// <summary>
    /// The rungs the <b>ladder tournament</b> ranks — everything settled on win rate, in ladder
    /// order.
    /// </summary>
    /// <remarks>
    /// <para>
    /// ⚠️ <b>Not a shorter list somebody typed, and the difference is the whole point</b>
    /// (BUILD-PLAN P18, P20, P23). It is <see cref="All"/> filtered by
    /// <see cref="BotRung.Ranked"/>, so a rung joins it by being a rung — and a rung that leaves
    /// it does so by declaring, in the catalog, where its number lives instead. <b>A rung cannot
    /// fall out of the programme by being forgotten</b>, which is what a hand-kept field allows
    /// and what P18 and P20 each had to remove one layer apart.
    /// </para>
    /// <para>
    /// ⚠️ <b>The ladder stopped being a line at P31, and the last entry stopped being the
    /// strongest with it.</b> Until <c>warden</c> every rung was one change from the rung before
    /// it, so "built upwards" and "in the order it was built" were the same order. <c>warden</c>
    /// and <c>prospector</c> are both one change from <c>outs</c> — a <em>branch</em> — so the
    /// list's tail is now whichever branch was written last, which is not a claim about strength
    /// at all. <b>What a stakes-sensitive rung is measured against is <see cref="Hardest"/></b>,
    /// which reads <see cref="BotRung.Strength"/> and so says what it means; <c>Ladder[^1]</c>
    /// merely used to agree with it. <c>StandingAnswerTests</c> asserts the property that is
    /// actually load-bearing — the strongest rung is one the ladder tournament ranks.
    /// </para>
    /// </remarks>
    public static IReadOnlyList<BotRung> Ladder { get; } =
        [.. All.Where(rung => rung.Ranked is RankedOn.WinRate)];

    /// <summary>
    /// The rungs the <b>money sweep</b> settles: those judged in dollars a round rather than in
    /// win rate (BUILD-PLAN P22, P44).
    /// </summary>
    /// <remarks>
    /// ⚠️ <b>Together with <see cref="Ladder"/> this is exactly <see cref="All"/></b>, which is
    /// how <c>sim suite</c> can promise to measure every rung there is without measuring one
    /// twice. ⚠️ <b>The name predates <c>purist</c></b>: <c>prospector</c> really does read the
    /// stakes, <c>purist</c> merely trades rounds for money — what the list collects is the
    /// rungs whose verdict is money, whichever of <see cref="RankedOn"/>'s two reasons put them
    /// there.
    /// </remarks>
    public static IReadOnlyList<BotRung> StakesSensitive { get; } =
        [.. All.Where(rung => rung.Ranked is RankedOn.Money)];

    /// <summary>
    /// The same rungs, <b>strongest first</b> — what a menu of opponents is ordered by.
    /// </summary>
    /// <remarks>
    /// Ties keep ladder order, so a level that measurement cannot split is shown in the order
    /// it was built. <b>A permutation of <see cref="All"/> and never a subset</b>, which is a
    /// test.
    /// </remarks>
    public static IReadOnlyList<BotRung> ByStrength { get; } =
        [.. All.OrderByDescending(rung => rung.Strength)];

    /// <summary>
    /// The strongest rung there is.
    /// </summary>
    /// <remarks>
    /// ⚠️ <b>What stands in for a seat nobody is answering, and what a hint is asked of</b> —
    /// neither of which is the table's difficulty setting. A stand-in that played worse than the
    /// table does would be worth less than no stand-in (P13.1), and a hint that got worse as you
    /// lowered the difficulty would be absurd. Both are said again where they are used, because
    /// both look like oversights to somebody tidying up.
    /// </remarks>
    public static BotRung Hardest => ByStrength[0];

    /// <summary>Looks a rung up by name, case-insensitively.</summary>
    /// <exception cref="ArgumentException">No rung is called that.</exception>
    public static BotRung Resolve(string name) =>
        Find(name)
        ?? throw new ArgumentException(
            $"No bot called '{name}'. Known: {string.Join(", ", All.Select(rung => rung.Name))}.", nameof(name));

    /// <summary>Looks a rung up by name, or null if there is none.</summary>
    /// <remarks>
    /// For a front end taking a name off a command line or a form, where an unknown one is
    /// something to fall back from rather than to throw over.
    /// </remarks>
    public static BotRung? Find(string? name) =>
        All.FirstOrDefault(rung => string.Equals(rung.Name, name, StringComparison.OrdinalIgnoreCase));
}
